### ISSUE TITLE
"Control does not support transparent background colors" exception when launching application

### ISSUE THREAD

**Issue by IanKemp** [fremag/MemoScope.Net#192]
Win10 x64, MemoScope 0.9.9.152 (latest release).

```
System.ArgumentException: Control does not support transparent background colors.
   at System.Windows.Forms.Control.set_BackColor(Color value)
   at System.Windows.Forms.ListView.set_BackColor(Color value)
   at WinFwk.UIModules.UIModuleForm.ApplyColors(Control control, UISettings uiSettings) in C:\projects\memoscope-net\WinFwk\UIModules\UIModuleForm.cs:line 269
   at WinFwk.UIModules.UIModuleForm.ApplyColors(Control control, UISettings uiSettings) in C:\projects\memoscope-net\WinFwk\UIModules\UIModuleForm.cs:line 280
   at WinFwk.UIModules.UIModuleForm.DockModule(UIModule uiModule, DockState dockState, Boolean allowclose) in C:\projects\memoscope-net\WinFwk\UIModules\UIModuleForm.cs:line 150
   at WinFwk.UIModules.UIModuleForm.InitWorkplace(WorkplaceModule workplace, DockState dockState) in C:\projects\memoscope-net\WinFwk\UIModules\UIModuleForm.Designer.cs:line 157
   at MemoScope.MemoScopeForm.MemoScope_Load(Object sender, EventArgs e) in C:\projects\memoscope-net\MemoScope\MemoScopeForm.cs:line 38
   at System.EventHandler.Invoke(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

Furthermore, after this exception, the app looks like this:

![image](https://cloud.githubusercontent.com/assets/1726434/22280666/e9085f40-e2da-11e6-9097-c22a1340af0c.png)

**Comment by IanKemp** [comment]
Looks like this happens after I run a master build (which writes config data) then run a 0.9.9.152 instance, which attempts to load that config file and obviously doesn't support the "new" values.

**Comment by fremag** [comment]
You're right : there is a bug in release 0.9.9 but fixed in master branch.
I will publish a new release 'RC1' with bug fixes commited since.
