### ISSUE TITLE
Unhandled exception when trying to access system directories

### ISSUE THREAD

**Issue by IanKemp** [fremag/MemoScope.Net#193]
Tested with latest release (0.99) and a build I made on my local machine using the latest master source, same issue on both. I simply pointed the app to my D:\ drive.

Fix is to not attempt to enumerate directories that have the `System` flag set.

Additionally, because the last directory you specified is stored in the application's XML configuration file, every subsequent run of the app will cause it to attempt to read that directory, which causes the aforementioned exception, which means the app can't be launched again until the XML config file is deleted or manually modified to point to a directory that doesn't cause this issue.

```
System.UnauthorizedAccessException: Access to the path 'D:\System Volume Information' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.DirectoryInfo.InternalGetFiles(String searchPattern, SearchOption searchOption)
   at MemoScope.Modules.Explorer.DirectoryData.get_CanExpand() in C:\projects\memoscope-net\MemoScope\Modules\Explorer\DirectoryData.cs:line 28
   at WinFwk.UITools.DefaultTreeListView.<>c__1`1.<InitData>b__1_0(Object o) in C:\projects\memoscope-net\WinFwk\UITools\DefaultTreeListView.cs:line 18
   at BrightIdeasSoftware.TreeListView.TreeRenderer.HandleHitTest(Graphics g, OlvListViewHitTestInfo hti, Int32 x, Int32 y)
   at BrightIdeasSoftware.BaseRenderer.HitTest(OlvListViewHitTestInfo hti, Int32 x, Int32 y)
   at BrightIdeasSoftware.ObjectListView.OlvHitTest(Int32 x, Int32 y)
   at BrightIdeasSoftware.ObjectListView.BuildCellEvent(CellEventArgs args, Point location)
   at BrightIdeasSoftware.ObjectListView.HandleMouseMove(Point pt)
   at BrightIdeasSoftware.ObjectListView.OnMouseMove(MouseEventArgs e)
   at System.Windows.Forms.Control.WmMouseMove(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ListView.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

**Comment by fremag** [comment]
Thanks for your help.
I will add some try/catch to avoid this.

**Comment by fremag** [comment]
![43](https://cloud.githubusercontent.com/assets/14943271/22388745/6bf897b8-e4e2-11e6-80bf-b0ccd3d45b84.png)

I've added some try/catch and exceptions are displayed in tooltip (in screenshot, the message is in french but means: "Access to path xxx is denied")
